import type { SpriteManifest } from "./types";

const MAIN_CHAR_WALK_FRAME_COUNT = 27;

function buildFrameSequence(direction: "left" | "right"): string[] {
  return Array.from({ length: MAIN_CHAR_WALK_FRAME_COUNT }, (_, index) => {
    const frame = String(index + 1).padStart(4, "0");
    return `/ingame_assets/characters/main_char/walk_${direction}_v2/frame_${frame}.png`;
  });
}

export const SKYHAVEN_SPRITE_MANIFEST: SpriteManifest = {
  tile: {
    base: {
      src: "/ingame_assets/expanded/island/tile_base.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    baseV2: {
      src: "/ingame_assets/expanded/island/tile_base_v2.png",
      drawW: 213,
      drawH: 213,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    baseV4: {
      src: "/ingame_assets/expanded/island/tile_base_v4.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    baseV7: {
      src: "/ingame_assets/expanded/island/tile_base_v7.png",
      drawW: 204,
      drawH: 204,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    grass: {
      src: "/ingame_assets/expanded/island/tile_grass.png",
      drawW: 208,
      drawH: 208,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    grassV2: {
      src: "/ingame_assets/expanded/island/tile_grass_v2.png",
      drawW: 196,
      drawH: 196,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    grassV4: {
      src: "/ingame_assets/expanded/island/tile_grass_v4.png",
      drawW: 208,
      drawH: 208,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 0,
    },
    pathCross: {
      src: "/ingame_assets/expanded/island/tile_path_cross.png",
      drawW: 216,
      drawH: 216,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathCrossV2: {
      src: "/ingame_assets/expanded/island/tile_path_cross_v2.png",
      drawW: 216,
      drawH: 216,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraight: {
      src: "/ingame_assets/expanded/island/tile_path_straight.png",
      drawW: 224,
      drawH: 206,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraightV4: {
      src: "/ingame_assets/expanded/island/tile_path_straight_v4.png",
      drawW: 218,
      drawH: 201,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraightV5: {
      src: "/ingame_assets/expanded/island/tile_path_straight_v5.png",
      drawW: 224,
      drawH: 206,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraightV6: {
      src: "/ingame_assets/expanded/island/tile_path_straight_v6.png",
      drawW: 207,
      drawH: 191,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraightAlt: {
      src: "/ingame_assets/expanded/island/tile_path_straight_alt.png",
      drawW: 212,
      drawH: 212,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraightAltV4: {
      src: "/ingame_assets/expanded/island/tile_path_straight_alt_v4.png",
      drawW: 200,
      drawH: 200,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    pathStraightAltV5: {
      src: "/ingame_assets/expanded/island/tile_path_straight_alt_v5.png",
      drawW: 212,
      drawH: 212,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    ancientStone: {
      src: "/ingame_assets/3d/AnicientStone_Tile.png",
      drawW: 216,
      drawH: 216,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    ancientStoneWall: {
      src: "/ingame_assets/3d/AnicientStoneWall_Tile.png",
      drawW: 216,
      drawH: 216,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    ancientCornerWall: {
      src: "/ingame_assets/3d/AnicientCornerStoneWall_Tile.png",
      drawW: 216,
      drawH: 216,
      anchorX: 0.5,
      anchorY: 0.71,
      layerOrder: 100,
    },
    tree1: {
      src: "/ingame_assets/expanded/island/tile_tree_1.png",
      drawW: 248,
      drawH: 248,
      anchorX: 0.5,
      anchorY: 0.76,
      layerOrder: 200,
      localYOffset: 45,
    },
    tree1V3: {
      src: "/ingame_assets/expanded/island/tile_tree_1_v3.png",
      drawW: 248,
      drawH: 248,
      anchorX: 0.5,
      anchorY: 0.76,
      layerOrder: 200,
      localYOffset: 45,
    },
    tree2: {
      src: "/ingame_assets/expanded/island/tile_tree_2.png",
      drawW: 298,
      drawH: 298,
      anchorX: 0.5,
      anchorY: 0.77,
      layerOrder: 200,
      localYOffset: 55,
    },
    tree2V0: {
      src: "/ingame_assets/expanded/island/tile_tree_2_v0.png",
      drawW: 288,
      drawH: 288,
      anchorX: 0.5,
      anchorY: 0.77,
      layerOrder: 200,
      localYOffset: 50,
    },
    tree2V1: {
      src: "/ingame_assets/expanded/island/tile_tree_2_v1.png",
      drawW: 298,
      drawH: 298,
      anchorX: 0.5,
      anchorY: 0.77,
      layerOrder: 200,
      localYOffset: 55,
    },
    mineTile: {
      src: "/ingame_assets/expanded/island/poi_mine_tile.png",
      drawW: 368,
      drawH: 368,
      anchorX: 0.5,
      anchorY: 0.8,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    mineTileV2: {
      src: "/ingame_assets/expanded/island/poi_mine_tile_v2.png",
      drawW: 368,
      drawH: 368,
      anchorX: 0.5,
      anchorY: 0.8,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    farmEmpty: {
      src: "/ingame_assets/expanded/farming/tile_farm_empty.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 0,
    },
    farmSlot: {
      src: "/ingame_assets/expanded/farming/tile_farm_slot.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 0,
    },
    farmHalf: {
      src: "/ingame_assets/expanded/farming/tile_farm_half_new.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 0,
    },
    farmFull: {
      src: "/ingame_assets/expanded/farming/tile_farm_full_new.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 0,
    },
    farmPath: {
      src: "/ingame_assets/expanded/farming/tile_farm_path.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 100,
    },
    farmPathCross: {
      src: "/ingame_assets/expanded/farming/tile_farm_path_cross.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 100,
    },
    farmPathStraight: {
      src: "/ingame_assets/expanded/farming/tile_farm_path_straight.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 100,
    },
    farmPathUp: {
      src: "/ingame_assets/expanded/farming/tile_farm_path_up.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 100,
    },
    farmPathDown: {
      src: "/ingame_assets/expanded/farming/tile_farm_path_down.png",
      drawW: 468,
      drawH: 468,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 100,
    },
    farmPoi: {
      src: "/ingame_assets/expanded/farming/tile_farm_poi.png",
      drawW: 936,
      drawH: 936,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    dirt: { src: "", drawW: 208, drawH: 208, anchorX: 0.5, anchorY: 0.71, layerOrder: 0 },
    treeMiddle: { src: "", drawW: 222, drawH: 222, anchorX: 0.5, anchorY: 0.65, layerOrder: 100 },
    farm2x2: { src: "/ingame_assets/expanded/toolbox/farm2x2_tile.png", drawW: 222, drawH: 222, anchorX: 0.5, anchorY: 0.65, layerOrder: 100 },
    poisFarming: { src: "/ingame_assets/expanded/farming/tile_farm_poi.png", drawW: 444, drawH: 444, anchorX: 0.5, anchorY: 0.65, layerOrder: 300, gridSpan: { w: 2, h: 2 } },
    grasBlumen: { src: "/ingame_assets/expanded/toolbox/gras_blumen_tile.png", drawW: 222, drawH: 222, anchorX: 0.5, anchorY: 0.65, layerOrder: 100 },
    taverne: { src: "/ingame_assets/expanded/taverne_island.png", drawW: 444, drawH: 444, anchorX: 0.5, anchorY: 0.65, layerOrder: 300, gridSpan: { w: 2, h: 2 } },
    floatingForge: {
      src: "/ingame_assets/3d/Floating_Forge.png",
      drawW: 444,
      drawH: 444,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    farmingChicken: {
      src: "/ingame_assets/3d/Farming_Chicken.png",
      drawW: 444,
      drawH: 444,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    bushTile: {
      src: "/ingame_assets/expanded/toolbox/bush_tile.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 200,
      localYOffset: 45,
    },
    statueAaron: {
      src: "",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
    },
    magicTower: {
      src: "/ingame_assets/3d/Magic_Tower.png",
      drawW: 444,
      drawH: 444,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    wellTile: {
      src: "/ingame_assets/3d/Well_Tile_Round.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 200,
      localYOffset: 50,
    },
    well2Tile: {
      src: "/ingame_assets/3d/Well_Tile_Square.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 200,
      localYOffset: 50,
    },
    halfGrownCropTile: {
      src: "/ingame_assets/3d/Half_grown_Crop_Tile.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 200,
      localYOffset: 50,
    },
    cottaTile: {
      src: "/ingame_assets/3d/Cottn_Tile.png",
      drawW: 444,
      drawH: 444,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    ancientTempleTile: {
      src: "/ingame_assets/3d/Temple_Tile.png",
      drawW: 444,
      drawH: 444,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    kaserneTile: {
      src: "/ingame_assets/3d/Kaserne_Tile.png",
      drawW: 444,
      drawH: 444,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 300,
      localYOffset: 80,
      gridSpan: { w: 2, h: 2 },
    },
    runeTile: {
      src: "/ingame_assets/3d/Rune_Tile.png",
      drawW: 222,
      drawH: 222,
      anchorX: 0.5,
      anchorY: 0.65,
      layerOrder: 200,
      localYOffset: 50,
    },
  },
  poi: {
    mine: {
      src: "/ingame_assets/expanded/island/poi_mine_tile.png",
      drawW: 380,
      drawH: 380,
      anchorX: 0.5,
      anchorY: 0.9,
    },
  },
  characters: {
    main: {
      walkLeft: buildFrameSequence("left"),
      walkRight: buildFrameSequence("right"),
      fps: 24,
      drawW: 66,
      drawH: 87,
      anchorX: 0.5,
      anchorY: 0.9,
    },
  },
  island: {
    complete: {
      src: "/ingame_assets/expanded/island/mining_complete.png",
      drawW: 1126,
      drawH: 989,
      anchorX: 0,
      anchorY: 0,
    },
  },
  ui: {
    background: "/ingame_assets/expanded/ui/background.png",
    border: "/ingame_assets/expanded/ui/border.png",
    compactBackground: "/ingame_assets/small/ui/background.png",
    compactBorder: "/ingame_assets/small/ui/border.png",
    compactStateBase: "/ingame_assets/small/ui/state_base.png",
    compactStateInventory: "/ingame_assets/small/ui/state_inventory.png",
    compactInventoryPanel: "/ingame_assets/small/inventory/panel.png",
    compactInventoryHeader: "/ingame_assets/small/inventory/header.png",
    compactInventoryTab: "/ingame_assets/small/inventory/tab.png",
    compactInventorySlot: "/ingame_assets/small/inventory/slot.png",
    sidebarButtonBg: "/ingame_assets/expanded/ui/sidebar_button_bg.png",
    focusPanelBg: "/ingame_assets/expanded/ui/focus_panel_bg.png",
    islandsPanelBg: "/ingame_assets/expanded/ui/islands/panel_bg.png",
    islandsArrowLeft: "/ingame_assets/expanded/ui/islands/arrow_left_circle.png",
    islandsArrowRight: "/ingame_assets/expanded/ui/islands/arrow_right_circle.png",
    labels: {
      mainMenu: "/ingame_assets/expanded/ui/label_main_menu.png",
      inventory: "/ingame_assets/expanded/ui/label_inventory.png",
      focusActions: "/ingame_assets/expanded/ui/label_focus_actions.png",
      shop: "/ingame_assets/expanded/ui/label_shop.png",
      islands: "/ingame_assets/expanded/ui/islands/label_islands.png",
      options: "/ingame_assets/expanded/ui/label_options.png",
      baukasten: "/ingame_assets/expanded/ui/label_focus_actions.png",
    },
    statusBg: "/ingame_assets/expanded/ui/status_bg.png",
    bars: {
      expTrack: "/ingame_assets/expanded/ui/bar_track_exp.png",
      expFill: "/ingame_assets/expanded/ui/bar_fill_exp.png",
      staminaTrack: "/ingame_assets/expanded/ui/bar_track_stamina.png",
      staminaFill: "/ingame_assets/expanded/ui/bar_fill_stamina.png",
    },
    chrome: {
      closeCircle: "/ingame_assets/expanded/ui/close_circle.png",
      closeLine1: "/ingame_assets/expanded/ui/close_line_1.png",
      closeLine2: "/ingame_assets/expanded/ui/close_line_2.png",
      expandCircle: "/ingame_assets/expanded/ui/expand_circle.png",
      expandArrow: "/ingame_assets/expanded/ui/expand_arrow.png",
      menuFrame: "/ingame_assets/expanded/ui/menu_btn_frame.png",
      menuCap: "/ingame_assets/expanded/ui/menu_btn_cap.png",
      menuLineH: "/ingame_assets/expanded/ui/menu_btn_line_h.png",
      menuLineV: "/ingame_assets/expanded/ui/menu_btn_line_v.png",
      menuInnerH: "/ingame_assets/expanded/ui/menu_btn_inner_h.png",
      menuInnerV: "/ingame_assets/expanded/ui/menu_btn_inner_v.png",
    },
  },
  scene: {
    centerXRatio: 0.67,
    centerYRatio: 0.66,
    compactCenterXRatio: 0.53,
    compactCenterYRatio: 0.58,
    debugGridSrc: "/ingame_assets/expanded/island/grid.png",
  },
};
